#!/bin/bash
make compile-verify > /dev/null
if [ $? -ne 0 ]
then
    echo "Note: Compiled files outdated, recompiling and committing."
    make compile
    git add agg-kicad.lib
    git add agg-kicad.pro
    git commit -m "Rebuild compiled files"
fi
