import sys
import datetime
import subprocess
import os.path


def git_version(libpath):
    args = ["git", "describe", "--abbrev=8", "--dirty=-dirty", "--always"]
    git = subprocess.Popen(args, cwd=libpath, stdout=subprocess.PIPE)
    return git.stdout.read().decode().strip()


def gnd(f, name):
    f.write('#\n# {}\n#\n'.format(name))
    f.write('DEF {} #PWR 0 40 N N 1 F P\n'.format(name))
    f.write('F0 "#PWR" -130 40 50 H I L CNN\n')
    f.write('F1 "{}" 0 -100 50 H V C CNN\n'.format(name))
    f.write('DRAW\n')
    f.write('P 2 0 1 0 0 0 0 -30 N\n')
    f.write('P 4 0 1 0 -30 -30 30 -30 0 -60 -30 -30 f\n')
    f.write('X {} 1 0 0 0 L 50 50 1 1 W N\n')
    f.write('ENDDRAW\nENDDEF\n#\n\n')


def pwr(f, name):
    f.write('#\n# {}\n#\n'.format(name))
    f.write('DEF {} #PWR 0 40 N N 1 F P\n'.format(name))
    f.write('F0 "#PWR" 0 110 50 H I L CNN\n')
    f.write('F1 "{}" 0 90 50 H V C CNN\n'.format(name))
    f.write('DRAW\n')
    f.write('P 2 0 1 0 0 50 20 20 N\n')
    f.write('P 3 0 1 0 0 0 0 50 -20 20 N\n')
    f.write('X {} 1 0 0 0 L 50 50 1 1 W N\n'.format(name))
    f.write('ENDDRAW\nENDDEF\n#\n\n')


def main(libpath):
    version = git_version(os.path.join(os.path.split(libpath)[-2]))
    f = open(libpath, "w")
    f.write("EESchema-LIBRARY Version 2.3\n")
    f.write("#encoding utf-8\n\n")
    f.write("#=====================================================\n")
    f.write("# Automatically generated by agg-kicad powerlib.py\n")
    f.write("# on {}\n".format(datetime.datetime.now()))
    f.write("# using git version {}\n".format(version))
    f.write("# See github.com/adamgreig/agg-kicad\n")
    f.write("#=====================================================\n\n")

    for name in ("VCC", "VDD", "AVCC", "1v8", "3v3", "5v", "VBATT"):
        pwr(f, name)
    for name in ("GND", "AGND", "DGND", "PGND"):
        gnd(f, name)

    f.write('# End Library\n')
    f.close()

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <lib path>".format(sys.argv[0]))
        sys.exit(1)

    main(sys.argv[1])
